### ISSUE TITLE
Please complete the documentation with the following information.

### ISSUE THREAD

**Issue by MalekJabri** [ibmbpm/Integration-Samples#1]
To integrate with mail, add a feature to the Liberty custom XML file that is set in the baw_configuration[x].liberty_custom_xml parameter. The following file is an example.
`
<server>
  <featureManager>
    
    <feature>javaMail-1.5</feature>
  </featureManager>
<server>
`

**Comment by gunnar-w** [comment]
In the latest versions of IBM Business Automation Workflow on Containers and IBM Cloud Pak for Business Automation the JavaMail feature is enabled automatically.
