### ISSUE TITLE
STARTTTLS is required to send mail

### ISSUE THREAD

**Issue by AilinLuca** [ibmbpm/Integration-Samples#2]
Receiving the following error when using the send mail service from the imported toolkit:

CWTBG0019E: Unexpected exception during execution. Exception information: 'com.lombardisoftware.component.common.workflow.WorkflowProcessItemException: An exception occurred in activity "Script Task" of "Service Flow" with name "AC Test Email Service". Task instance id "Task.626". Details: "451 5.7.3 STARTTLS is required to send mail [SN6PR05CA0024.namprd05.prod.outlook.com] ".'.

Thanks for your help if you know what that is.

**Comment by gunnar-w** [comment]
The sample code does only support unsecured SMTP servers. The error suggests that you are trying to send mail from a secured SMTP server. You may consider to download the source code and adapt to your project requirements.
